name: Testim E2E
on: [push]

jobs:
  run-testimio-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: yarn install

      - name: Install Google Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Install Chrome Driver
        run: sudo apt-get install -y chromium-chromedriver

      - name: Run Testim CLI
        run: yarn testim
